services:
  nginx:
    image: nginx:1.27.5-alpine3.21
    container_name: nginx
    hostname: nginx
    ports:
      - "127.0.0.1:80:80"
      - "443:443"
    volumes:
      - ./certificates:/etc/ssl/certs/nginx:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/html:/var/www/html:ro
      - ./nginx/includes:/etc/nginx/includes:ro
    environment:
      TZ: UTC
    healthcheck:
      test: curl -f http://127.0.0.1 || exit 1
      interval: 1s
      timeout: 2s
      retries: 5
    links:
      - gitlab-server
      - localmail
      - nexus
      - sonar
